/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lunatech_example_sietse_StackSearch_VINDRank */

#ifndef _Included_com_lunatech_example_sietse_StackSearch_VINDRank
#define _Included_com_lunatech_example_sietse_StackSearch_VINDRank
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lunatech_example_sietse_StackSearch_VINDRank
 * Method:    attachVINDRank
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_lunatech_example_sietse_StackSearch_VINDRank_attachVINDRank
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
